FROM debian:stable-slim
RUN apt-get update
RUN apt-get install -y python3-pip git
RUN pip3 install dockerfile_parse requests gitpython
COPY biotools-patch.py /root/
COPY dockerparse_arg_fix.py /root/
RUN mkdir -p /root/.ssh
RUN echo "Host github.com\n\tStrictHostKeyChecking no" >> /root/.ssh/config

ENTRYPOINT ["/usr/bin/python3", "/root/biotools-patch.py"]
