apiVersion: v1
kind: ReplicationController
metadata:
  name: ci-proxy 
spec:
  replicas: 1
  template:
    metadata:
      labels:
         app: ci-proxy
    spec:
      containers:
      - name: ci-proxy
        image: biocontainers/ci-proxy 
        env:
          - name: "JENKINS_URL"
            value: "http://jenkins:30752"
          - name: "GITHUB_STATUS_TOKEN"
            valueFrom:
              secretKeyRef:
                name: github
                key: status_token
        ports:
          - containerPort: 9080
