apiVersion: v1
kind: Service
metadata:
  name: ci-proxy
  labels:
    app: ci-proxy
spec:
  type: NodePort
  ports:
   - name: http 
     port: 9080
     nodePort: 30753
  selector:
    app: ci-proxy
